### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by jmank88** [gochain/netstats#16]
Error while monitoring a high volume load test:
```
buffer.js:67
    super(arg1, arg2, arg3);
    ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at typedArrayConstructByLength (<anonymous>)
    at new Uint8Array (native)
    at new FastBuffer (buffer.js:67:5)
    at Function.alloc (buffer.js:267:10)
    at new Buffer (buffer.js:168:19)
    at BufferPool.reset (/netstats/node_modules/ws/lib/BufferPool.js:57:26)
    at Receiver.endPacket (/netstats/node_modules/ws/lib/Receiver.js:256:68)
    at Receiver.finish (/netstats/node_modules/ws/lib/Receiver.js:542:12)
    at Receiver.expectHandler (/netstats/node_modules/ws/lib/Receiver.js:493:33)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gochain-netstats@0.0.15 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gochain-netstats@0.0.15 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-18T01_53_47_856Z-debug.log
```

**Comment by jmank88** [comment]
This happens often. Perhaps we are retaining too much history.

**Comment by jmank88** [comment]
Sometimes it's more severe, and requires `service docker restart`.

Logs:
```
#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
Illegal instruction (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! gochain-netstats@0.0.17 start: `node ./bin/www`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the gochain-netstats@0.0.17 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-19T00_42_57_974Z-debug.log
```

Attempting to stop/rm/kill the containers results in something like:
```
Error response from daemon: cannot stop container: netstats: Cannot kill container b7ce6fe3a5cb3f5374e70c35440688ddf836bc831350711e6c53ddcc551765bb: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown
```

**Comment by rkononov** [comment]
all good
